export interface FoodItemCreated {
    idfirestore?: string;
    originalMealId?: string;
    idDoc?: string;
    id: string;
    idUser: string;
    title: string;
    calories: number;
    carbohydrates: number;
    fats: number;
    proteins: number;
    quantity: number;
    unit: string;
    sugar?: number;
    vitaminA?: number;
    vitaminB1?:number;
    vitaminB5?:number;
    vitaminB6?:number;
    vitaminB12?:number;
    vitaminC?:number;
    vitaminD?:number;
    folate?:number;
    vitaminE?: number;
    vitaminK?:number;
    potassium?:number;
    magnesium?: number;
    calcium?:number;
    sodium?: number;
    iron?: number;
    cholesterol?: number;
}